### ISSUE TITLE
データの保存方法を決定する

### ISSUE THREAD

**Issue by Sab-swiftlin** [continue-dev/ios-game#3]
ユーザーの能力値や状態などを保存しておく必要があるため、どこに保存するかなど保存方法を決定する。

**Comment by minmin0530** [comment]
唯一使ったことがあるRealmが良いかなと思います。

**Comment by Sab-swiftlin** [comment]
ありがとうございます。
そうですね、Realmなら特に問題なさそうなのでそれでいきますか。

**Comment by minmin0530** [comment]
では、Realmでお願いします。

**Comment by minmin0530** [comment]
#12 がこの要件を満たしていると思うので、このIssueを閉じても良いでしょうか？ @Sab-swiftlin

**Comment by Sab-swiftlin** [comment]
そうですね、close致します。
