### ISSUE TITLE
共通のナビゲーションバーを実装する

### ISSUE THREAD

**Issue by Sab-swiftlin** [continue-dev/ios-game#4]
ホーム画面などで画面上部に表示されているステータス部分を複数画面で共通化できるように実装する。

![課題選択画面3](https://user-images.githubusercontent.com/50907353/69811881-6b889780-1232-11ea-8338-4b9c8a154a83.jpg)

**Comment by minmin0530** [comment]
List画面、ListViewControllerみたいなのを作る必要があると思います。

**Comment by Sab-swiftlin** [comment]
そうですね、それはナビゲーション部分とは別画面になると思います。

**Comment by minmin0530** [comment]
このIssueではナビゲーションクラスのような物で、ホーム画面や課題リスト画面でナビゲーションバーを共有出来るものを作るということで良いでしょうか。

**Comment by Sab-swiftlin** [comment]
UINavigationBar部分がステータスになっているUINavigationController的なものを自作するイメージです。

**Comment by minmin0530** [comment]
では、これをプルリクしていただくか、
https://github.com/continue-dev/ios-game/commit/54214ed3e8356005b9d07968e2a667c85e3edf35
もしくは、このブランチのまま共通ナビゲーションは Sab さんにお任せするか、していいですか？

**Comment by Sab-swiftlin** [comment]
あ、すいません、今作業途中だったのでそのまま実装します。
分かりにくいので今後は先にWIPでPRたてるようにしますね。

**Comment by Sab-swiftlin** [comment]
あ、すいません、今作業途中だったのでそのまま実装します。
分かりにくいので今後は先にWIPでPRたてるようにしますね。

**Comment by minmin0530** [comment]
WIPについて今まで知りませんでした。ググったのでなんとなく理解しました。
ではWIPでPRお願いします。
